config/routes.rb
Rails.application.routes.draw do
  resources :queries
  devise_for :users
  resources :students
  resources :tests
  resources :scholars
  get '/' => 'scholars#open'
  get '/tests/open' => 'tests#open'

end

app/models/student.rb
class Student < ActiveRecord::Base

	validates_format_of:email,:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates_presence_of :Name,:phone,:email,:income,:cgpa,:community,:DOB
	
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:Name, :DOB, :community, :income, :cgpa, :phone, :email)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :DOB %><br>
    <%= f.text_field :DOB %>
  </div>
  <div class="field">
    <%= f.label :community %><br>
    <%= f.text_field :community %>
  </div>
  <div class="field">
    <%= f.label :income %><br>
    <%= f.number_field :income %>
  </div>
  <div class="field">
    <%= f.label :cgpa %><br>
    <%= f.text_field :cgpa %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th>Community</th>
      <th>Income</th>
      <th>Cgpa</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.Name %></td>
        <td><%= student.DOB %></td>
        <td><%= student.community %></td>
        <td><%= student.income %></td>
        <td><%= student.cgpa %></td>
        <td><%= student.phone %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<!DOCTYPE HTML>
<!--
  Landed by HTML5 UP
  html5up.net | @n33co
  Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
  <head>
    <title>Scholarships</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    "scholarship", :media => "all" %>
    
  </head>
  <body>
    <div id="page-wrapper">

      <!-- Header -->
        <header id="header">
          
          <nav id="nav">
            <ul>
              <li><a href="/scholars">Scholarship</a></li>
              <li><a href="/tests">Test </a></li>
              <li><a href="syllabus.html">Syllabus</a></li>
              <li>
                <a href="/">Home</a>
              </li>
              <li><a href="/users/sign_up" class="button special">Sign Up</a></li>
            </ul>
          </nav>
        </header>

      <!-- Main -->
        <div id="main" class="wrapper style1">
          <div class="container">
            <header class="major">
              <h2>Application Form</h2>
              
            </header>
            
              
              <div class="8u$ 12u$(medium) important(medium)">

                <!-- Content -->
                  <p id="notice"><%= notice %></p>


<%= render 'form' %>

<%= link_to 'Back', students_path %>

<br>


              
            
          </div>
        </div>

      

    </div>

    <!-- Scripts -->
      <script src="assets/js/jquery.min.js"></script>
      <script src="assets/js/jquery.scrolly.min.js"></script>
      <script src="assets/js/jquery.dropotron.min.js"></script>
      <script src="assets/js/jquery.scrollex.min.js"></script>
      <script src="assets/js/skel.min.js"></script>
      <script src="assets/js/util.js"></script>
      <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
      <script src="assets/js/main.js"></script>

  </body>
</html>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.Name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @student.DOB %>
</p>

<p>
  <strong>Community:</strong>
  <%= @student.community %>
</p>

<p>
  <strong>Income:</strong>
  <%= @student.income %>
</p>

<p>
  <strong>Cgpa:</strong>
  <%= @student.cgpa %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>