config/routes.rb
Rails.application.routes.draw do
  resources :queries
  devise_for :users
  resources :students
  resources :tests
  resources :scholars
  get '/' => 'scholars#open'
  get '/tests/open' => 'tests#open'

end

app/models/scholar.rb
class Scholar < ActiveRecord::Base
end

app/controllers/scholars_controller.rb
class ScholarsController < ApplicationController
  before_action :set_scholar, only: [:show, :edit, :update, :destroy]

  # GET /scholars
  # GET /scholars.json
  def index
    @scholars = Scholar.all
  end

  # GET /scholars/1
  # GET /scholars/1.json
  def show
  end

  # GET /scholars/new
  def new
    @scholar = Scholar.new
  end

  # GET /scholars/1/edit
  def edit
  end

  # POST /scholars
  # POST /scholars.json
  def create
    @scholar = Scholar.new(scholar_params)

    respond_to do |format|
      if @scholar.save
        format.html { redirect_to @scholar, notice: 'Scholar was successfully created.' }
        format.json { render :show, status: :created, location: @scholar }
      else
        format.html { render :new }
        format.json { render json: @scholar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholars/1
  # PATCH/PUT /scholars/1.json
  def update
    respond_to do |format|
      if @scholar.update(scholar_params)
        format.html { redirect_to @scholar, notice: 'Scholar was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholar }
      else
        format.html { render :edit }
        format.json { render json: @scholar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholars/1
  # DELETE /scholars/1.json
  def destroy
    @scholar.destroy
    respond_to do |format|
      format.html { redirect_to scholars_url, notice: 'Scholar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholar
      @scholar = Scholar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scholar_params
      params.require(:scholar).permit(:Name, :Description, :Provider, :Due)
    end
end

app/helpers/scholars_helper.rb
module ScholarsHelper
end

app/views/scholars/_form.html.erb
<%= form_for(@scholar) do |f| %>
  <% if @scholar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scholar.errors.count, "error") %> prohibited this scholar from being saved:</h2>

      <ul>
      <% @scholar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
    
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :Provider %><br>
    <%= f.text_field :Provider %>
  </div>
  <div class="field">
    <%= f.label :Due %><br>
    <%= f.date_select :Due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/scholars/edit.html.erb
<h1>Editing Scholar</h1>

<%= render 'form' %>

<%= link_to 'Show', @scholar %> |
<%= link_to 'Back', scholars_path %>

app/views/scholars/index.html.erb
<!DOCTYPE HTML>
<!--
  Landed by HTML5 UP
  html5up.net | @n33co
  Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
  <head>
    <title>Scholarships</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    "scholarship", :media => "all" %>
    
  </head>
  <body>
    <div id="page-wrapper">

      <!-- Header -->
        <header id="header">
          
          <nav id="nav">
            <ul>
              <li><a href="scholar.html">Scholarship</a></li>
              <li><a href="take_test.html">Test </a></li>
              <li><a href="syllabus.html">Syllabus</a></li>
              <li>
                <a href="/">Home</a>
              </li>
              <li><a href="new.html" class="button special">Sign Up</a></li>
            </ul>
          </nav>
        </header>

      <!-- Main -->
        <div id="main" class="wrapper style1">
          <div class="container">
            <header class="major">
              <h2>Scholarships</h2>
              
            </header>
            
              
              <div class="8u$ 12u$(medium) important(medium)">

                <!-- Content -->
                  <p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Provider</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scholars.each do |scholar| %>
      <tr>
        <td><%= scholar.Name %></td>
        <td><%= scholar.Description %></td>
        <td><%= scholar.Provider %></td>
        <td><%= scholar.Due %></td>
        <td><%= link_to 'Show', scholar %></td>
        <td><%= link_to 'Edit', edit_scholar_path(scholar) %></td>
        <td><%= link_to 'Destroy', scholar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scholar', new_scholar_path %>

              
            
          </div>
        </div>

      

    </div>

    <!-- Scripts -->
      <script src="assets/js/jquery.min.js"></script>
      <script src="assets/js/jquery.scrolly.min.js"></script>
      <script src="assets/js/jquery.dropotron.min.js"></script>
      <script src="assets/js/jquery.scrollex.min.js"></script>
      <script src="assets/js/skel.min.js"></script>
      <script src="assets/js/util.js"></script>
      <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
      <script src="assets/js/main.js"></script>

  </body>
</html>

app/views/scholars/new.html.erb
<!DOCTYPE HTML>
<!--
  Landed by HTML5 UP
  html5up.net | @n33co
  Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
  <head>
    <title>Scholarships</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    "scholarship", :media => "all" %>
    
  </head>
  <body>
    <div id="page-wrapper">

      <!-- Header -->
        <header id="header">
          
          <nav id="nav">
            <ul>
              <li><a href="/scholars">Scholarship</a></li>
              <li><a href="/tests">Test </a></li>
              <li><a href="syllabus.html">Syllabus</a></li>
              <li>
                <a href="/">Home</a>
              </li>
              <li><a href="/users/sign_up" class="button special">Sign Up</a></li>
            </ul>
          </nav>
        </header>

      <!-- Main -->
        <div id="main" class="wrapper style1">
          <div class="container">
            <header class="major">
              <h2>Scholarships</h2>
              
            </header>
            
              
              <div class="8u$ 12u$(medium) important(medium)">

                <!-- Content -->
                  <p id="notice"><%= notice %></p>


<%= render 'form' %>

<%= link_to 'Back', scholars_path %>

<br>


              
            
          </div>
        </div>

      

    </div>

    <!-- Scripts -->
      <script src="assets/js/jquery.min.js"></script>
      <script src="assets/js/jquery.scrolly.min.js"></script>
      <script src="assets/js/jquery.dropotron.min.js"></script>
      <script src="assets/js/jquery.scrollex.min.js"></script>
      <script src="assets/js/skel.min.js"></script>
      <script src="assets/js/util.js"></script>
      <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
      <script src="assets/js/main.js"></script>

  </body>
</html>

app/views/scholars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scholar.Name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scholar.Description %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @scholar.Provider %>
</p>

<p>
  <strong>Due:</strong>
  <%= @scholar.Due %>
</p>

<%= link_to 'Edit', edit_scholar_path(@scholar) %> |
<%= link_to 'Back', scholars_path %>